name: Automatisation des tests
on: push

jobs:
  Compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurer le build
        run: |
          mkdir build
          cd build
          cmake ..
          
      - name: Compiler
        run: |
          cd build
          make
          
      - name: Sauvegarder les artefacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: build/

  Test_Add:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - uses: actions/checkout@v4
      
      - name: Récupérer les artefacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/
          
      - name: Test fonction add
        run: ./build/src/calculator add 10 5

  Test_sub:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - uses: actions/checkout@v4
      
      - name: Récupérer les artefacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/
          
      - name: Test fonction sub
        run: ./build/src/calculator sub 10 5

  Test_mul:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - uses: actions/checkout@v4
      
      - name: Récupérer les artefacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/
          
      - name: Test fonction mul
        run: ./build/src/calculator mul 10 5

  Test_div:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - uses: actions/checkout@v4
      
      - name: Récupérer les artefacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/
          
      - name: Test fonction div
        run: ./build/src/calculator div 10 5

  Test_car:
    runs-on: ubuntu-latest
    needs: Compilation
    steps:
      - uses: actions/checkout@v4
      
      - name: Récupérer les artefacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts
          path: build/
          
      - name: Test fonction car
        run: ./build/src/calculator car 3

  Deployment:
    runs-on: ubuntu-latest
    needs: [Test_Add, Test_sub, Test_mul, Test_div, Test_car]
    steps:
      - name: Déploiement de la solution
        run: echo "Déploiement de la solution"